const EmailOtp = (() => {
    let config = null;
    let configPromise = null;
    let initialized = false;

    function normalizeConfig(rawConfig) {
        return Object.freeze({
            publicKey: String(rawConfig?.public_key || rawConfig?.publicKey || '').trim(),
            serviceId: String(rawConfig?.service_id || rawConfig?.serviceId || '').trim(),
            templateId: String(rawConfig?.template_id || rawConfig?.templateId || '').trim(),
            appName: String(rawConfig?.app_name || rawConfig?.appName || 'MediSeba').trim() || 'MediSeba',
            otpExpiryMinutes: Number(rawConfig?.otp_expiry_minutes || rawConfig?.otpExpiryMinutes || 5) || 5,
            otpDeliveryMode: String(rawConfig?.otp_delivery_mode || rawConfig?.otpDeliveryMode || 'server_emailjs').trim() || 'server_emailjs'
        });
    }

    async function loadConfig() {
        if (config) {
            return config;
        }

        if (!configPromise) {
            configPromise = fetch(`${API_BASE_URL}/api/config/public`, {
                method: 'GET',
                headers: {
                    'Accept': 'application/json'
                }
            })
                .then(async (response) => {
                    const payload = await response.json();

                    if (!response.ok || !payload?.success) {
                        throw new Error(payload?.message || 'Failed to load EmailJS configuration.');
                    }

                    return normalizeConfig({
                        ...(payload?.data?.email_otp || {}),
                        app_name: payload?.data?.app_name,
                        otp_expiry_minutes: payload?.data?.otp_expiry_minutes,
                        otp_delivery_mode: payload?.data?.otp_delivery_mode
                    });
                })
                .then((resolvedConfig) => {
                    config = resolvedConfig;
                    return config;
                })
                .catch((error) => {
                    configPromise = null;
                    throw error;
                });
        }

        return configPromise;
    }

    function ensureConfigured(runtimeConfig) {
        const missing = [];

        if (!runtimeConfig.publicKey) missing.push('public key');
        if (!runtimeConfig.serviceId) missing.push('service ID');
        if (!runtimeConfig.templateId) missing.push('template ID');

        if (missing.length > 0) {
            throw new Error(`EmailJS is missing: ${missing.join(', ')}. Please add them to the backend .env file.`);
        }
    }

    function formatConfigError(error) {
        const message = String(error?.message || '').trim();

        return new Error(
            message || 'Unable to load EmailJS configuration for OTP delivery.'
        );
    }

    async function ensureInitialized() {
        if (initialized) {
            return;
        }

        if (!window.emailjs) {
            throw new Error('EmailJS SDK failed to load.');
        }

        const runtimeConfig = await loadConfig().catch((error) => {
            throw formatConfigError(error);
        });

        ensureConfigured(runtimeConfig);
        window.emailjs.init(runtimeConfig.publicKey);
        initialized = true;
    }

    function formatError(error) {
        const status = error?.status ? ` (${error.status})` : '';
        const message = String(error?.text || error?.message || '').trim();
        const normalizedMessage = message || 'Unknown EmailJS error';

        return new Error(
            `Failed to send the OTP email${status}. Please check your EmailJS service, template, public key, and template variables. ${normalizedMessage}`.trim()
        );
    }

    async function sendOtp(email, otp, context = 'login') {
        await ensureInitialized();

        if (!email) {
            throw new Error('A valid email address is required before sending the OTP.');
        }

        if (!otp) {
            throw new Error('The OTP was not generated by the server.');
        }

        try {
            const runtimeConfig = await loadConfig();

            return await window.emailjs.send(runtimeConfig.serviceId, runtimeConfig.templateId, {
                to_email: email,
                email,
                user_email: email,
                recipient_email: email,
                otp_code: otp,
                otp,
                passcode: otp,
                app_name: runtimeConfig.appName,
                company_name: runtimeConfig.appName,
                brand_name: runtimeConfig.appName,
                otp_expiry_minutes: runtimeConfig.otpExpiryMinutes,
                validity_minutes: runtimeConfig.otpExpiryMinutes,
                login_context: context
            });
        } catch (error) {
            throw formatError(error);
        }
    }

    return {
        getConfig: loadConfig,
        sendOtp
    };
})();
